### ISSUE TITLE
Bad practice to consider single confidence level for interval score?

### ISSUE THREAD

**Issue by sgbaird** [uncertainty-toolbox/uncertainty-toolbox#57]
@YoungseogChung and @jdpsc,

I've been [discussing UQ quality metrics](https://github.com/ml-evs/modnet-matbench/issues/18) and which underlying UQ metric to use in a materials informatics benchmarking scheme called [matbench](https://matbench.materialsproject.org/). If we use a single score (e.g. the interval score for just 95% confidence interval rather than a mean of interval scores using CIs ranging from 1% to 99%) via:
https://github.com/uncertainty-toolbox/uncertainty-toolbox/blob/b2f342f6606d1d667bf9583919a663adf8643efe/uncertainty_toolbox/metrics_scoring_rule.py#L190-L197
what pitfalls can you see from using this approach? Would this be considered bad practice?

The trade-off is that we either ask users for ~100x more information in submitting their benchmarks or have the fallback of asking for a single set of intervals (e.g. 95%) or a few sets of intervals (e.g. 90% + 95% + 99%) which doesn't seem to be in line with the uncertainty toolbox's implementation which scans over a range of intervals. Another alternative is we just ask users for `y_std`, but this [may limit usefulness for certain applications](https://github.com/ml-evs/modnet-matbench/issues/18#issuecomment-1007830808).

**Comment by YoungseogChung** [comment]
Hi @sgbaird, thanks for your question and we apologize for the slow response.

Using the interval score to evaluate the prediction interval for a single coverage level is completely valid, and if the quality of specifically the 95% PI is crucial in the application or benchmarking scheme, then we do not see any issues in just evaluating the 95% PI. 

The reason why our implementations consider the mean of the score across a range of coverage levels is because we were concerned with evaluating the full predictive distribution, whereas a single PI provides only a single facet of this distribution. 
As you mention, the 95% PI is quite standard when comparing UQ methods - however, it certainly may be the case that method A's 95% PI achieves a better interval score than method B's, but method A's 70% PI achieves a worse interval score than method B's. 
Hence, for the purpose of conducting a holistic evaluation of the predictive distribution, we believe it's advantageous to consider a range of coverage levels, but again, if the focus is on just the 95% PI, we believe it's completely fine to compute the metrics for just the 95% PI. 

P.S. Thanks also for your issues and comments on installation - we are discussing your suggestions and will get back to you on those issues soon!
